Feature/kpi and translation
reload/ding2 pull request #27
Opened 2017-03-06 11:48 UTC by troelslenda

2017-03-08 13:47 UTC, achton requested changes
@troelslenda Lots of changes here, but nothing major overall. Looks great to me!

Just needs some polishing and search/replace voodoo.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.info
> +dependencies[] = xautoload
X Autoload is not enabled in Ding2 by default it seems, and has no "Cache mode" enabled by default (see /admin/config/development/performance). Not sure how to handle this, but the config form says:

> X Autoload will pick the first cache mode that is available and enabled.
Currently, this is: No cache..

So although loadinng Guzzle works, it seems that out of the box, we are not gaining anything from X Autoload unless we make sure to configure it properly for the user as well.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.admin.inc
> +  $form['additional_search']['#title'] = t('Additional Search');
I think the proper title is "Ting Subsearch settings".

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.admin.inc
> +  $form['additional_search']['#title'] = t('Additional Search');
I think the proper title is "Ting Subsearch settings".

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +  $form['additional_search']['#title'] = t('Ting Subsearch');
I think the proper title is "Ting Subsearch settings".

The form array keys should be renamed as well (sorry!) :)

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.module
> +  if ($results->numTotalObjects <= variable_get('do_you_mean_case_4_minimum', 5)) {
This should be a separate setting, not one from another Subsearch module. But the same text changes from above apply here.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#title' => t('Minimum results for case 4'),
It should be clearer what this setting is about, and not refer to our own specs from JIRA. A better title:

"Number of hits to trigger KPI subsearch"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#description' => t('In order to trigger case 4 we need a minimum of results.'),
Better description: "In order to trigger a subsearch which will provide a suggestion to the user, the user-provided search string must trigger *at most* this number of hits. NOTE: User-provided searches that trigger 0 hits always trigger a subsearch."

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#default_value' => variable_get('do_you_mean_case_4_minimum', 5),
Better variable name: `subsearch_kpi_trigger_limit`

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +  $form['additional_search']['do_you_mean_guess'] = array(
One thought here: we are creating an inherent relationship between the KPI and Open Suggestion subsearch modules here, because they each add to the `$options` list here. Instead of doing that, we could separate the two modules entirely, and simply recommend in the docs that they are not both enabled at the same time, because support for that is not yet implemented. It could be implemented at a later time (maybe by someone else). That would make it easier to sort out the configuration for sites that already use one of the modules.

Also, if they cannot be used together, why even enable both of them at the same time? :)

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#title' => t('Guess engine'),
I would call this "Suggestion service".

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#default_value' => variable_get('do_you_mean_guess', FALSE),
I would rename `do_you_mean_guess` to `subsearch_kpi_suggestion_service` or `subsearch_suggestion_service`.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +  $default_value = 'https://ws.webtrends.com/v3/Reporting/profiles/77577/reports/sprt2Xll7b7/';
I don't think it makes sense to have a default value for the Webtrends data hardcoded into the module.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#title' => t('Webservice Endpoint'),
It should be "KPI Webtrends On-Site Searches Web Service URL".

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#description' => t('Text to be determined'),
> This field must contain the "Web Services" URL to the "On-Site Searches" report that can be found in Webtrends Analytics in the *Content* category. Click the *Share* button on the report page to find this URL."

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    'end_period' => 'current_day-1',
I think start and end period should be contracted to just "How many days back do you want to fetch report data for?" We can calculate the raw parameters based on that integer value from the user.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    'format' => 'json',
Is there any reason to allow this to be configurable? We don't support any of the other formats (Excel, XML).

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +      '#description' => t('Text to be determined'),
This description should be left out, or be part of the parameter array above, so it can be different for each parameter.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#type' => 'textfield',
This should be split out into a field for account, and another for username. Too much risk that people put in spaces, or a forward slash instead of backslash, etc. 
We can build the proper auth string based on the individual string components.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +  $form['additional_search']['do_you_mean_kpi'] = array(
I think `do_you_mean_kpi` should simply be `kpi` or ` kpi_settings` here and below.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +    $query = db_insert('kpi_index_popular_keys')->fields(
Remember here, that `levenshtein()` cannot handle more than 255 characters in a string, so we could filter out rows that have that before inserting here.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#description' => t('The max allowed distance between words for it to be similar. Higher distance, less similarity.'),
I think the correct description is "Enter the maximum [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance) here, ie. the maximum number of characters to replace, insert or delete to transform the input string into a string from the KPI data. A higher numbere allows for less similar words to be suggested."

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#title' => t('Minimum of searches for keys'),
"Minimum search import limit"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.admin.inc
> +    '#description' => t('The KPI Index has a lot of keys with only 1 search. But how few is minimum?'),
"The KPI Webtrends data has search keywords for all searches, including searches with very low frequence (eg. searched only 1 time). Enter the number of minimum searches required before a keyword is imported and used in the KPI subsearch."

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.install
> +        'description' => 'The number of times the keys was searched',
"keys" = "key"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.install
> +  $json = json_decode(file_get_contents(drupal_get_path('module', 'subsearch_kpi') . '/kpi_index.json'));
I guess this install hook can be removed now?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +// Load Field module hooks.
Not sure what this comment means?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +  // the visitor.
The wrapping seems off here, is this 80 columns?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/plugins/content_types/search_result.inc
> +  ting_search_search_execute($keys, array('sort' => ''));
If we could pass the name of the cache key we want to use here, we could get rid of a lot of this juggling around, no? Is it worth expanding the `ting_search_search_execute()` function for that?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +    // Find suggestions for "correct" search phrase.
"Find suggestions for a corrected search phrase."

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.info
> +version = 0.1
We could add a configuration hint here:

`configure = admin/config/ting/settings`

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.info
> +version = 0.1
We could add a configuration hint here:

`configure = admin/config/ting/settings`

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.info
> +version = 0.1
We could add a configuration hint here:

`configure = admin/config/ting/settings`

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.admin.inc
> +  $options['os'] = t('OpenSuggestion');
The correct service name is actually "Open Suggestion Service".

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.info
> +name = Subsearch OpenSuggestion - What Did You Mean?
"Ting Subsearch - Open Suggestion Service"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.info
> +name = Subsearch KPI - What Did You Mean?
"Ting Subsearch - KPI Webtrends suggestions"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.info
> +name = Subsearch Translate search
"Ting Subsearch - Translate keyword"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.info
> +description = Extend Ting Search with secondary search
Extend Ting Search with secondary search which translates the search to English and informs user if relevant.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +    if ($distance < variable_get('do_you_mean_kpi_distance', 0)) {
`levenshtein()` will return -1 on fail - that should be accounted for here.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +    watchdog('subsearch_kpi', 'Data fetched from KPI. Will re-run in day.', array(), WATCHDOG_INFO);
"... Will re-run in *a* day." :)

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.module
> + * Enables search integration with Ting.
Copy paste comment?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> + * Enables search integration with Ting.
Copy paste comment?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_opensuggestion/subsearch_opensuggestion.module
> +
Too many newlines here.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +    ),
Are all these libraries necessary to declare for GuzzleHttp to function properly?

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.admin.inc
> +    '#type' => 'textfield',
I think the settings for the Subsearch Translation module should be in a separate fieldset as well.

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.admin.inc
> +    '#title' => t('Translated Search: Google Apikey'),
"Google Cloud Translation API key"

2017-03-08 13:47 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.module
> +  // Simply exit for now.
This whole criterion seems very weird and specific to me (fiction vs non-fiction). Should we make it optional, with just a checkbox to enable it? Might make this translation subsearch feature more usable to others.

2017-03-09 08:49 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +    $query = db_insert('kpi_index_popular_keys')->fields(
Agreed with client: We filter out strings that contain an equal sign `=`

2017-03-09 09:33 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.module
> +  if (($nonfiction/2) > $fiction) {
Agreed with client: Expose the `2` as a configurable setting. Either directly or recalculated to a percentage value.

2017-03-09 09:42 UTC, achton commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +
This query needs to take into accout the original key, so we do not return that same key again. This avoids suggesting the original key to the user again.

2017-03-09 14:21 UTC, troelslenda commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.module
> +  // the visitor.
less

2017-03-09 14:21 UTC, troelslenda commented on modules/ting_search/modules/subsearch_kpi/subsearch_kpi.install
> +        'description' => 'The number of times the keys was searched',
keys

2017-03-13 09:44 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.install
> +  variable_del('translated_suggestion_google_key');
This needs to be renamed to `translation_google_key`.

2017-03-13 09:44 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.install
> +    if (preg_match('/^\s*[a-zA-Z0-9]{39}$/', variable_get('translated_suggestion_google_key', ''))) {
`translation_google_key`

2017-03-13 09:44 UTC, achton commented on modules/ting_search/modules/subsearch_translate/subsearch_translate.install
> +      'title' => $t('Google Apikey'),
"Google Cloud Translation API key"

2017-03-16 14:12 UTC, achton approved these changes
LGTM! :+1: 

![](http://i.giphy.com/S24vAZeES2INy.gif)

2017-03-17 07:33 UTC, merged